// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: proto/publish_build_event.proto

package publish_build_event

import (
	build_events "github.com/buildbuddy-io/reninja/genproto/build_events"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The service level of the build request. Backends only uses this value when
// the BuildEnqueued event is published to determine what level of service
// this build should receive.
type PublishLifecycleEventRequest_ServiceLevel int32

const (
	// Non-interactive builds can tolerate longer event latencies. This is the
	// default ServiceLevel if callers do not specify one.
	PublishLifecycleEventRequest_NONINTERACTIVE PublishLifecycleEventRequest_ServiceLevel = 0
	// The events of an interactive build should be delivered with low latency.
	PublishLifecycleEventRequest_INTERACTIVE PublishLifecycleEventRequest_ServiceLevel = 1
)

// Enum value maps for PublishLifecycleEventRequest_ServiceLevel.
var (
	PublishLifecycleEventRequest_ServiceLevel_name = map[int32]string{
		0: "NONINTERACTIVE",
		1: "INTERACTIVE",
	}
	PublishLifecycleEventRequest_ServiceLevel_value = map[string]int32{
		"NONINTERACTIVE": 0,
		"INTERACTIVE":    1,
	}
)

func (x PublishLifecycleEventRequest_ServiceLevel) Enum() *PublishLifecycleEventRequest_ServiceLevel {
	p := new(PublishLifecycleEventRequest_ServiceLevel)
	*p = x
	return p
}

func (x PublishLifecycleEventRequest_ServiceLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PublishLifecycleEventRequest_ServiceLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_publish_build_event_proto_enumTypes[0].Descriptor()
}

func (PublishLifecycleEventRequest_ServiceLevel) Type() protoreflect.EnumType {
	return &file_proto_publish_build_event_proto_enumTypes[0]
}

func (x PublishLifecycleEventRequest_ServiceLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PublishLifecycleEventRequest_ServiceLevel.Descriptor instead.
func (PublishLifecycleEventRequest_ServiceLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_publish_build_event_proto_rawDescGZIP(), []int{0, 0}
}

// Publishes 'lifecycle events' that update the high-level state of a build:
//   - BuildEnqueued: When a build is scheduled.
//   - InvocationAttemptStarted: When work for a build starts; there can be
//     multiple invocations for a build (e.g. retries).
//   - InvocationAttemptCompleted: When work for a build finishes.
//   - BuildFinished: When a build is finished.
type PublishLifecycleEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The interactivity of this build.
	ServiceLevel PublishLifecycleEventRequest_ServiceLevel `protobuf:"varint,1,opt,name=service_level,json=serviceLevel,proto3,enum=google.devtools.build.v1.PublishLifecycleEventRequest_ServiceLevel" json:"service_level,omitempty"`
	// Required. The lifecycle build event. If this is a build tool event, the RPC
	// will fail with INVALID_REQUEST.
	BuildEvent *OrderedBuildEvent `protobuf:"bytes,2,opt,name=build_event,json=buildEvent,proto3" json:"build_event,omitempty"`
	// If the next event for this build or invocation (depending on the event
	// type) hasn't been published after this duration from when {build_event}
	// is written to BES, consider this stream expired. If this field is not set,
	// BES backend will use its own default value.
	StreamTimeout *durationpb.Duration `protobuf:"bytes,3,opt,name=stream_timeout,json=streamTimeout,proto3" json:"stream_timeout,omitempty"`
	// Additional information about a build request. These are define by the event
	// publishers, and the Build Event Service does not validate or interpret
	// them. They are used while notifying internal systems of new builds and
	// invocations if the OrderedBuildEvent.event type is
	// BuildEnqueued/InvocationAttemptStarted.
	NotificationKeywords []string `protobuf:"bytes,4,rep,name=notification_keywords,json=notificationKeywords,proto3" json:"notification_keywords,omitempty"`
	// Required. The project this build is associated with.
	// This should match the project used for the initial call to
	// PublishLifecycleEvent (containing a BuildEnqueued message).
	ProjectId string `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Whether to require a previously received matching parent lifecycle event
	// for the current request's event before continuing processing.
	//   - InvocationAttemptStarted and BuildFinished events require a BuildEnqueued
	//     parent event.
	//   - InvocationAttemptFinished events require an InvocationAttemptStarted
	//     parent event.
	CheckPrecedingLifecycleEventsPresent bool `protobuf:"varint,7,opt,name=check_preceding_lifecycle_events_present,json=checkPrecedingLifecycleEventsPresent,proto3" json:"check_preceding_lifecycle_events_present,omitempty"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *PublishLifecycleEventRequest) Reset() {
	*x = PublishLifecycleEventRequest{}
	mi := &file_proto_publish_build_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishLifecycleEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishLifecycleEventRequest) ProtoMessage() {}

func (x *PublishLifecycleEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publish_build_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishLifecycleEventRequest.ProtoReflect.Descriptor instead.
func (*PublishLifecycleEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_publish_build_event_proto_rawDescGZIP(), []int{0}
}

func (x *PublishLifecycleEventRequest) GetServiceLevel() PublishLifecycleEventRequest_ServiceLevel {
	if x != nil {
		return x.ServiceLevel
	}
	return PublishLifecycleEventRequest_NONINTERACTIVE
}

func (x *PublishLifecycleEventRequest) GetBuildEvent() *OrderedBuildEvent {
	if x != nil {
		return x.BuildEvent
	}
	return nil
}

func (x *PublishLifecycleEventRequest) GetStreamTimeout() *durationpb.Duration {
	if x != nil {
		return x.StreamTimeout
	}
	return nil
}

func (x *PublishLifecycleEventRequest) GetNotificationKeywords() []string {
	if x != nil {
		return x.NotificationKeywords
	}
	return nil
}

func (x *PublishLifecycleEventRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PublishLifecycleEventRequest) GetCheckPrecedingLifecycleEventsPresent() bool {
	if x != nil {
		return x.CheckPrecedingLifecycleEventsPresent
	}
	return false
}

// States which event has been committed. Any failure to commit will cause
// RPC errors, hence not recorded by this proto.
type PublishBuildToolEventStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stream that contains this event.
	StreamId *build_events.StreamId `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// The sequence number of this event that has been committed.
	SequenceNumber int64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PublishBuildToolEventStreamResponse) Reset() {
	*x = PublishBuildToolEventStreamResponse{}
	mi := &file_proto_publish_build_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBuildToolEventStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBuildToolEventStreamResponse) ProtoMessage() {}

func (x *PublishBuildToolEventStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publish_build_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBuildToolEventStreamResponse.ProtoReflect.Descriptor instead.
func (*PublishBuildToolEventStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_publish_build_event_proto_rawDescGZIP(), []int{1}
}

func (x *PublishBuildToolEventStreamResponse) GetStreamId() *build_events.StreamId {
	if x != nil {
		return x.StreamId
	}
	return nil
}

func (x *PublishBuildToolEventStreamResponse) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

// Build event with contextual information about the stream it belongs to and
// its position in that stream.
type OrderedBuildEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which build event stream this event belongs to.
	StreamId *build_events.StreamId `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// The position of this event in the stream. The sequence numbers for a build
	// event stream should be a sequence of consecutive natural numbers starting
	// from one. (1, 2, 3, ...)
	SequenceNumber int64 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	// The actual event.
	Event         *build_events.BuildEvent `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderedBuildEvent) Reset() {
	*x = OrderedBuildEvent{}
	mi := &file_proto_publish_build_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderedBuildEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderedBuildEvent) ProtoMessage() {}

func (x *OrderedBuildEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publish_build_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderedBuildEvent.ProtoReflect.Descriptor instead.
func (*OrderedBuildEvent) Descriptor() ([]byte, []int) {
	return file_proto_publish_build_event_proto_rawDescGZIP(), []int{2}
}

func (x *OrderedBuildEvent) GetStreamId() *build_events.StreamId {
	if x != nil {
		return x.StreamId
	}
	return nil
}

func (x *OrderedBuildEvent) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *OrderedBuildEvent) GetEvent() *build_events.BuildEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// Streaming request message for PublishBuildToolEventStream.
type PublishBuildToolEventStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The build event with position info.
	// New publishing clients should use this field rather than the 3 above.
	OrderedBuildEvent *OrderedBuildEvent `protobuf:"bytes,4,opt,name=ordered_build_event,json=orderedBuildEvent,proto3" json:"ordered_build_event,omitempty"`
	// The keywords to be attached to the notification which notifies the start
	// of a new build event stream. BES only reads this field when sequence_number
	// or ordered_build_event.sequence_number is 1 in this message. If this field
	// is empty, BES will not publish notification messages for this stream.
	NotificationKeywords []string `protobuf:"bytes,5,rep,name=notification_keywords,json=notificationKeywords,proto3" json:"notification_keywords,omitempty"`
	// Required. The project this build is associated with.
	// This should match the project used for the initial call to
	// PublishLifecycleEvent (containing a BuildEnqueued message).
	ProjectId string `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Whether to require a previously received matching InvocationAttemptStarted
	// event before continuing event processing for the event in the current
	// request. BES only performs this check for events with sequence_number 1
	// i.e. the first event in the stream.
	CheckPrecedingLifecycleEventsPresent bool `protobuf:"varint,7,opt,name=check_preceding_lifecycle_events_present,json=checkPrecedingLifecycleEventsPresent,proto3" json:"check_preceding_lifecycle_events_present,omitempty"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *PublishBuildToolEventStreamRequest) Reset() {
	*x = PublishBuildToolEventStreamRequest{}
	mi := &file_proto_publish_build_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBuildToolEventStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBuildToolEventStreamRequest) ProtoMessage() {}

func (x *PublishBuildToolEventStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_publish_build_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBuildToolEventStreamRequest.ProtoReflect.Descriptor instead.
func (*PublishBuildToolEventStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_publish_build_event_proto_rawDescGZIP(), []int{3}
}

func (x *PublishBuildToolEventStreamRequest) GetOrderedBuildEvent() *OrderedBuildEvent {
	if x != nil {
		return x.OrderedBuildEvent
	}
	return nil
}

func (x *PublishBuildToolEventStreamRequest) GetNotificationKeywords() []string {
	if x != nil {
		return x.NotificationKeywords
	}
	return nil
}

func (x *PublishBuildToolEventStreamRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *PublishBuildToolEventStreamRequest) GetCheckPrecedingLifecycleEventsPresent() bool {
	if x != nil {
		return x.CheckPrecedingLifecycleEventsPresent
	}
	return false
}

var File_proto_publish_build_event_proto protoreflect.FileDescriptor

const file_proto_publish_build_event_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/publish_build_event.proto\x12\x18google.devtools.build.v1\x1a\x18proto/build_events.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/api/client.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x83\x04\n" +
	"\x1cPublishLifecycleEventRequest\x12h\n" +
	"\rservice_level\x18\x01 \x01(\x0e2C.google.devtools.build.v1.PublishLifecycleEventRequest.ServiceLevelR\fserviceLevel\x12Q\n" +
	"\vbuild_event\x18\x02 \x01(\v2+.google.devtools.build.v1.OrderedBuildEventB\x03\xe0A\x02R\n" +
	"buildEvent\x12@\n" +
	"\x0estream_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\rstreamTimeout\x123\n" +
	"\x15notification_keywords\x18\x04 \x03(\tR\x14notificationKeywords\x12\"\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tB\x03\xe0A\x02R\tprojectId\x12V\n" +
	"(check_preceding_lifecycle_events_present\x18\a \x01(\bR$checkPrecedingLifecycleEventsPresent\"3\n" +
	"\fServiceLevel\x12\x12\n" +
	"\x0eNONINTERACTIVE\x10\x00\x12\x0f\n" +
	"\vINTERACTIVE\x10\x01\"\x8f\x01\n" +
	"#PublishBuildToolEventStreamResponse\x12?\n" +
	"\tstream_id\x18\x01 \x01(\v2\".google.devtools.build.v1.StreamIdR\bstreamId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x03R\x0esequenceNumber\"\xb9\x01\n" +
	"\x11OrderedBuildEvent\x12?\n" +
	"\tstream_id\x18\x01 \x01(\v2\".google.devtools.build.v1.StreamIdR\bstreamId\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x03R\x0esequenceNumber\x12:\n" +
	"\x05event\x18\x03 \x01(\v2$.google.devtools.build.v1.BuildEventR\x05event\"\xb7\x02\n" +
	"\"PublishBuildToolEventStreamRequest\x12`\n" +
	"\x13ordered_build_event\x18\x04 \x01(\v2+.google.devtools.build.v1.OrderedBuildEventB\x03\xe0A\x02R\x11orderedBuildEvent\x123\n" +
	"\x15notification_keywords\x18\x05 \x03(\tR\x14notificationKeywords\x12\"\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tB\x03\xe0A\x02R\tprojectId\x12V\n" +
	"(check_preceding_lifecycle_events_present\x18\a \x01(\bR$checkPrecedingLifecycleEventsPresent2\xde\x04\n" +
	"\x11PublishBuildEvent\x12\xc9\x01\n" +
	"\x15PublishLifecycleEvent\x126.google.devtools.build.v1.PublishLifecycleEventRequest\x1a\x16.google.protobuf.Empty\"`\x82\xd3\xe4\x93\x02Z:\x01*Z :\x01*\"\x1b/v1/lifecycleEvents:publish\"3/v1/projects/{project_id=*}/lifecycleEvents:publish\x12\xa6\x02\n" +
	"\x1bPublishBuildToolEventStream\x12<.google.devtools.build.v1.PublishBuildToolEventStreamRequest\x1a=.google.devtools.build.v1.PublishBuildToolEventStreamResponse\"\x85\x01\xdaA4ordered_build_event,notification_keywords,project_id\x82\xd3\xe4\x93\x02H:\x01*Z\x17:\x01*\"\x12/v1/events:publish\"*/v1/projects/{project_id=*}/events:publish(\x010\x01\x1aT\xcaA buildeventservice.googleapis.com\xd2A.https://www.googleapis.com/auth/cloud-platformB\x88\x01\n" +
	"\x1ccom.google.devtools.build.v1B\fBackendProtoP\x01Z=github.com/buildbuddy-io/reninja/genproto/publish_build_event\xf8\x01\x01\xca\x02\x15Google\\Cloud\\Build\\V1b\x06proto3"

var (
	file_proto_publish_build_event_proto_rawDescOnce sync.Once
	file_proto_publish_build_event_proto_rawDescData []byte
)

func file_proto_publish_build_event_proto_rawDescGZIP() []byte {
	file_proto_publish_build_event_proto_rawDescOnce.Do(func() {
		file_proto_publish_build_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_publish_build_event_proto_rawDesc), len(file_proto_publish_build_event_proto_rawDesc)))
	})
	return file_proto_publish_build_event_proto_rawDescData
}

var file_proto_publish_build_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_publish_build_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_publish_build_event_proto_goTypes = []any{
	(PublishLifecycleEventRequest_ServiceLevel)(0), // 0: google.devtools.build.v1.PublishLifecycleEventRequest.ServiceLevel
	(*PublishLifecycleEventRequest)(nil),           // 1: google.devtools.build.v1.PublishLifecycleEventRequest
	(*PublishBuildToolEventStreamResponse)(nil),    // 2: google.devtools.build.v1.PublishBuildToolEventStreamResponse
	(*OrderedBuildEvent)(nil),                      // 3: google.devtools.build.v1.OrderedBuildEvent
	(*PublishBuildToolEventStreamRequest)(nil),     // 4: google.devtools.build.v1.PublishBuildToolEventStreamRequest
	(*durationpb.Duration)(nil),                    // 5: google.protobuf.Duration
	(*build_events.StreamId)(nil),                  // 6: google.devtools.build.v1.StreamId
	(*build_events.BuildEvent)(nil),                // 7: google.devtools.build.v1.BuildEvent
	(*emptypb.Empty)(nil),                          // 8: google.protobuf.Empty
}
var file_proto_publish_build_event_proto_depIdxs = []int32{
	0, // 0: google.devtools.build.v1.PublishLifecycleEventRequest.service_level:type_name -> google.devtools.build.v1.PublishLifecycleEventRequest.ServiceLevel
	3, // 1: google.devtools.build.v1.PublishLifecycleEventRequest.build_event:type_name -> google.devtools.build.v1.OrderedBuildEvent
	5, // 2: google.devtools.build.v1.PublishLifecycleEventRequest.stream_timeout:type_name -> google.protobuf.Duration
	6, // 3: google.devtools.build.v1.PublishBuildToolEventStreamResponse.stream_id:type_name -> google.devtools.build.v1.StreamId
	6, // 4: google.devtools.build.v1.OrderedBuildEvent.stream_id:type_name -> google.devtools.build.v1.StreamId
	7, // 5: google.devtools.build.v1.OrderedBuildEvent.event:type_name -> google.devtools.build.v1.BuildEvent
	3, // 6: google.devtools.build.v1.PublishBuildToolEventStreamRequest.ordered_build_event:type_name -> google.devtools.build.v1.OrderedBuildEvent
	1, // 7: google.devtools.build.v1.PublishBuildEvent.PublishLifecycleEvent:input_type -> google.devtools.build.v1.PublishLifecycleEventRequest
	4, // 8: google.devtools.build.v1.PublishBuildEvent.PublishBuildToolEventStream:input_type -> google.devtools.build.v1.PublishBuildToolEventStreamRequest
	8, // 9: google.devtools.build.v1.PublishBuildEvent.PublishLifecycleEvent:output_type -> google.protobuf.Empty
	2, // 10: google.devtools.build.v1.PublishBuildEvent.PublishBuildToolEventStream:output_type -> google.devtools.build.v1.PublishBuildToolEventStreamResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_publish_build_event_proto_init() }
func file_proto_publish_build_event_proto_init() {
	if File_proto_publish_build_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_publish_build_event_proto_rawDesc), len(file_proto_publish_build_event_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_publish_build_event_proto_goTypes,
		DependencyIndexes: file_proto_publish_build_event_proto_depIdxs,
		EnumInfos:         file_proto_publish_build_event_proto_enumTypes,
		MessageInfos:      file_proto_publish_build_event_proto_msgTypes,
	}.Build()
	File_proto_publish_build_event_proto = out.File
	file_proto_publish_build_event_proto_goTypes = nil
	file_proto_publish_build_event_proto_depIdxs = nil
}
