// Code generated by re2go 4.3 on Thu Oct 16 14:46:23 2025, DO NOT EDIT.
//
//go:generate re2go -i $GOFILE -o lexer.go --api generic
package lexer

import (
	"fmt"
	"strings"

	"github.com/buildbuddy-io/gin/internal/eval_env"
)

// Token represents a lexical token
type Token int

const (
	ERROR Token = iota
	BUILD
	COLON
	DEFAULT
	EQUALS
	IDENT
	INCLUDE
	INDENT
	NEWLINE
	PIPE2
	PIPE
	PIPEAT
	POOL
	RULE
	SUBNINJA
	EOF
)

// TokenName returns a human-readable form of a token
func TokenName(t Token) string {
	switch t {
	case ERROR:
		return "lexing error"
	case BUILD:
		return "'build'"
	case COLON:
		return "':'"
	case DEFAULT:
		return "'default'"
	case EQUALS:
		return "'='"
	case IDENT:
		return "identifier"
	case INCLUDE:
		return "'include'"
	case INDENT:
		return "indent"
	case NEWLINE:
		return "newline"
	case PIPE:
		return "'|'"
	case PIPE2:
		return "'||'"
	case PIPEAT:
		return "'|@'"
	case POOL:
		return "'pool'"
	case RULE:
		return "'rule'"
	case SUBNINJA:
		return "'subninja'"
	case EOF:
		return "eof"
	default:
		return fmt.Sprintf("unknown(%d)", t)
	}
}

// TokenErrorHint returns a hint for expected tokens
func TokenErrorHint(expected Token) string {
	switch expected {
	case COLON:
		return " ($ also escapes ':')"
	default:
		return ""
	}
}

// Lexer tokenizes ninja build files
type Lexer struct {
	filename  string
	input     string
	ofs       int // current offset in input (like C++ ofs_)
	lastToken int // position of last token (like C++ last_token_)
}

// New creates a new Lexer
func New() *Lexer {
	return &Lexer{}
}

func (l *Lexer) DumpState() string {
	sprintf := func(lastToken int) string {
		if lastToken == -1 {
			return "(null)"
		}
		return l.input[lastToken:]
	}

	return fmt.Sprintf("ofs: [%d] '%s', lastToken: [%d] '%s'\n", l.ofs, l.input[l.ofs:], l.lastToken, sprintf(l.lastToken))
}

// NewWithInput creates a new Lexer with input
func NewWithInput(input string) *Lexer {
	l := &Lexer{}
	l.Start("input", input)
	return l
}

// Start initializes the lexer with input
func (l *Lexer) Start(filename, input string) {
	l.filename = filename
	l.input = input
	l.ofs = 0
	l.lastToken = -1
}

// DescribeLastError returns the last error message
func (l *Lexer) DescribeLastError() string {
	if l.lastToken < len(l.input) {
		switch l.input[l.lastToken] {
		case '\t':
			return "tabs are not allowed, use spaces"
		}
	}
	return "lexing error"
}

// Error constructs an error message with context
func (l *Lexer) Error(message string) error {
	// Compute line/column
	line := 1
	lineStart := 0
	for i := 0; i < l.lastToken && i < len(l.input); i++ {
		if l.input[i] == '\n' {
			line++
			lineStart = i + 1
		}
	}
	col := 0
	if l.lastToken != 0 {
		col = l.lastToken - lineStart
	}

	errMsg := fmt.Sprintf("%s:%d: %s\n", l.filename, line, message)

	// Add some context to the message
	const truncateColumn = 72
	if col > 0 && col < truncateColumn {
		truncated := true
		var length int
		for length = lineStart; length < truncateColumn; length++ {
			if length >= len(l.input) || l.input[length] == '\n' {
				truncated = false
				break
			}
		}

		errMsg += l.input[lineStart:length]
		if truncated {
			errMsg += "..."
		}
		errMsg += "\n" + strings.Repeat(" ", col) + "^ near here"
	}
	return fmt.Errorf("%s", errMsg)
}

// UnreadToken rewinds to the last read token
func (l *Lexer) UnreadToken() {
	l.ofs = l.lastToken
}

// ReadToken reads the next token
func (l *Lexer) ReadToken() Token {
	var cursor, marker, start int
	cursor = l.ofs
	limit := len(l.input)
	var token Token
	for {
		start = cursor

		{
			var yych byte
			yyaccept := 0
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 0x00:
				goto yy1
			case '\n':
				goto yy4
			case '\r':
				goto yy5
			case ' ':
				goto yy6
			case '#':
				goto yy8
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a':
				fallthrough
			case 'c':
				fallthrough
			case 'e', 'f', 'g', 'h':
				fallthrough
			case 'j', 'k', 'l', 'm', 'n', 'o':
				fallthrough
			case 'q':
				fallthrough
			case 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy9
			case ':':
				goto yy12
			case '=':
				goto yy13
			case 'b':
				goto yy14
			case 'd':
				goto yy15
			case 'i':
				goto yy16
			case 'p':
				goto yy17
			case 'r':
				goto yy18
			case 's':
				goto yy19
			case '|':
				goto yy20
			default:
				goto yy2
			}
		yy1:
			cursor += 1
			{
				token = EOF
				break
			}
		yy2:
			cursor += 1
		yy3:
			{
				token = ERROR
				break
			}
		yy4:
			cursor += 1
			{
				token = NEWLINE
				break
			}
		yy5:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '\n':
				goto yy22
			default:
				goto yy3
			}
		yy6:
			yyaccept = 0
			cursor += 1
			marker = cursor
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '\n':
				goto yy4
			case '\r':
				goto yy23
			case ' ':
				goto yy6
			case '#':
				goto yy25
			default:
				goto yy7
			}
		yy7:
			{
				token = INDENT
				break
			}
		yy8:
			yyaccept = 1
			cursor += 1
			marker = cursor
			yych = peek(l.input, cursor, limit)
			if yych <= 0x00 {
				goto yy3
			}
			goto yy26
		yy9:
			cursor += 1
			yych = peek(l.input, cursor, limit)
		yy10:
			switch yych {
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy9
			default:
				goto yy11
			}
		yy11:
			{
				token = IDENT
				break
			}
		yy12:
			cursor += 1
			{
				token = COLON
				break
			}
		yy13:
			cursor += 1
			{
				token = EQUALS
				break
			}
		yy14:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'u':
				goto yy28
			default:
				goto yy10
			}
		yy15:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'e':
				goto yy29
			default:
				goto yy10
			}
		yy16:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'n':
				goto yy30
			default:
				goto yy10
			}
		yy17:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'o':
				goto yy31
			default:
				goto yy10
			}
		yy18:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'u':
				goto yy32
			default:
				goto yy10
			}
		yy19:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'u':
				goto yy33
			default:
				goto yy10
			}
		yy20:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '@':
				goto yy34
			case '|':
				goto yy35
			default:
				goto yy21
			}
		yy21:
			{
				token = PIPE
				break
			}
		yy22:
			cursor += 1
			{
				token = NEWLINE
				break
			}
		yy23:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '\n':
				goto yy22
			default:
				goto yy24
			}
		yy24:
			cursor = marker
			if yyaccept == 0 {
				goto yy7
			} else {
				goto yy3
			}
		yy25:
			cursor += 1
			yych = peek(l.input, cursor, limit)
		yy26:
			switch yych {
			case 0x00:
				goto yy24
			case '\n':
				goto yy27
			default:
				goto yy25
			}
		yy27:
			cursor += 1
			{
				continue
			}
		yy28:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'i':
				goto yy36
			default:
				goto yy10
			}
		yy29:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'f':
				goto yy37
			default:
				goto yy10
			}
		yy30:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'c':
				goto yy38
			default:
				goto yy10
			}
		yy31:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'o':
				goto yy39
			default:
				goto yy10
			}
		yy32:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'l':
				goto yy40
			default:
				goto yy10
			}
		yy33:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'b':
				goto yy41
			default:
				goto yy10
			}
		yy34:
			cursor += 1
			{
				token = PIPEAT
				break
			}
		yy35:
			cursor += 1
			{
				token = PIPE2
				break
			}
		yy36:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'l':
				goto yy42
			default:
				goto yy10
			}
		yy37:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'a':
				goto yy43
			default:
				goto yy10
			}
		yy38:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'l':
				goto yy44
			default:
				goto yy10
			}
		yy39:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'l':
				goto yy45
			default:
				goto yy10
			}
		yy40:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'e':
				goto yy47
			default:
				goto yy10
			}
		yy41:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'n':
				goto yy49
			default:
				goto yy10
			}
		yy42:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'd':
				goto yy50
			default:
				goto yy10
			}
		yy43:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'u':
				goto yy52
			default:
				goto yy10
			}
		yy44:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'u':
				goto yy53
			default:
				goto yy10
			}
		yy45:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy9
			default:
				goto yy46
			}
		yy46:
			{
				token = POOL
				break
			}
		yy47:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy9
			default:
				goto yy48
			}
		yy48:
			{
				token = RULE
				break
			}
		yy49:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'i':
				goto yy54
			default:
				goto yy10
			}
		yy50:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy9
			default:
				goto yy51
			}
		yy51:
			{
				token = BUILD
				break
			}
		yy52:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'l':
				goto yy55
			default:
				goto yy10
			}
		yy53:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'd':
				goto yy56
			default:
				goto yy10
			}
		yy54:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'n':
				goto yy57
			default:
				goto yy10
			}
		yy55:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 't':
				goto yy58
			default:
				goto yy10
			}
		yy56:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'e':
				goto yy60
			default:
				goto yy10
			}
		yy57:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'j':
				goto yy62
			default:
				goto yy10
			}
		yy58:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy9
			default:
				goto yy59
			}
		yy59:
			{
				token = DEFAULT
				break
			}
		yy60:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy9
			default:
				goto yy61
			}
		yy61:
			{
				token = INCLUDE
				break
			}
		yy62:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 'a':
				goto yy63
			default:
				goto yy10
			}
		yy63:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy9
			default:
				goto yy64
			}
		yy64:
			{
				token = SUBNINJA
				break
			}
		}

	}

	l.lastToken = start
	l.ofs = cursor
	if token != NEWLINE && token != EOF {
		l.EatWhitespace()
	}
	return token
}

// PeekToken checks if the next token matches
func (l *Lexer) PeekToken(token Token) bool {
	t := l.ReadToken()
	if t == token {
		return true
	}
	l.UnreadToken()
	return false
}

// EatWhitespace skips trailing whitespace after tokens
func (l *Lexer) EatWhitespace() {
	var cursor, marker int
	cursor = l.ofs
	limit := len(l.input)
	for {
		l.ofs = cursor

		{
			var yych byte
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 0x00:
				goto yy66
			case ' ':
				goto yy69
			case '$':
				goto yy71
			default:
				goto yy67
			}
		yy66:
			cursor += 1
			{
				break
			}
		yy67:
			cursor += 1
		yy68:
			{
				break
			}
		yy69:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case ' ':
				goto yy69
			default:
				goto yy70
			}
		yy70:
			{
				continue
			}
		yy71:
			cursor += 1
			marker = cursor
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '\n':
				goto yy72
			case '\r':
				goto yy73
			default:
				goto yy68
			}
		yy72:
			cursor += 1
			{
				continue
			}
		yy73:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '\n':
				goto yy75
			default:
				goto yy74
			}
		yy74:
			cursor = marker
			goto yy68
		yy75:
			cursor += 1
			{
				continue
			}
		}

	}
}

// Returns "fake" terminating null if cursor has reached limit.
func peek(str string, cursor, limit int) byte {
	if cursor >= limit {
		return 0 // fake null
	} else {
		return str[cursor]
	}
}

func (l *Lexer) ReadIdent() (string, bool) {
	cursor := l.ofs
	var start int
	limit := len(l.input)
	for {
		start = cursor

		{
			var yych byte
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy78
			default:
				goto yy77
			}
		yy77:
			cursor += 1
			{
				l.lastToken = start
				return "", false
			}
		yy78:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy78
			default:
				goto yy79
			}
		yy79:
			{
				out := string(l.input[start:cursor])
				l.lastToken = start
				l.ofs = cursor
				l.EatWhitespace()
				return out, true
			}
		}

	}
}

func (l *Lexer) ReadPath() (*eval_env.EvalString, error) {
	return l.ReadEvalString(true)
}

func (l *Lexer) ReadVarValue() (*eval_env.EvalString, error) {
	return l.ReadEvalString(false)
}

func (l *Lexer) ReadEvalString(path bool) (*eval_env.EvalString, error) {
	eval := &eval_env.EvalString{}
	limit := len(l.input)
	var cursor, marker, start int
	cursor = l.ofs

	for {
		start = cursor

		{
			var yych byte
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 0x00:
				goto yy81
			case '\n':
				fallthrough
			case ' ':
				fallthrough
			case ':':
				fallthrough
			case '|':
				goto yy84
			case '\r':
				goto yy85
			case '$':
				goto yy87
			default:
				goto yy82
			}
		yy81:
			cursor += 1
			{
				l.lastToken = start
				return nil, fmt.Errorf("unexpected EOF")
			}
		yy82:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case 0x00:
				fallthrough
			case '\n':
				fallthrough
			case '\r':
				fallthrough
			case ' ':
				fallthrough
			case '$':
				fallthrough
			case ':':
				fallthrough
			case '|':
				goto yy83
			default:
				goto yy82
			}
		yy83:
			{
				eval.AddText(string(l.input[start:cursor]))
				continue
			}
		yy84:
			cursor += 1
			{
				if path {
					cursor = start
					goto done
				} else {
					if l.input[start] == '\n' {
						goto done
					}
					eval.AddText(string(l.input[start : start+1]))
					continue
				}
			}
		yy85:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '\n':
				goto yy88
			default:
				goto yy86
			}
		yy86:
			{
				l.lastToken = start
				return nil, l.Error(l.DescribeLastError())
			}
		yy87:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '\n':
				goto yy91
			case '\r':
				goto yy93
			case ' ':
				goto yy94
			case '$':
				goto yy95
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy96
			case ':':
				goto yy98
			case '{':
				goto yy99
			default:
				goto yy89
			}
		yy88:
			cursor += 1
			{
				if path {
					cursor = start
				}
				goto done
			}
		yy89:
			cursor += 1
		yy90:
			{
				l.lastToken = start
				return nil, l.Error("bad $-escape (literal $ must be written as $$)")
			}
		yy91:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case ' ':
				goto yy91
			default:
				goto yy92
			}
		yy92:
			{
				continue
			}
		yy93:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '\n':
				goto yy100
			default:
				goto yy90
			}
		yy94:
			cursor += 1
			{
				eval.AddText(" ")
				continue
			}
		yy95:
			cursor += 1
			{
				eval.AddText("$")
				continue
			}
		yy96:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '-':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy96
			default:
				goto yy97
			}
		yy97:
			{
				eval.AddSpecial(string(l.input[start+1 : start+cursor-start]))
				continue
			}
		yy98:
			cursor += 1
			{
				eval.AddText(":")
				continue
			}
		yy99:
			cursor += 1
			marker = cursor
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy102
			default:
				goto yy90
			}
		yy100:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case ' ':
				goto yy100
			default:
				goto yy101
			}
		yy101:
			{
				continue
			}
		yy102:
			cursor += 1
			yych = peek(l.input, cursor, limit)
			switch yych {
			case '-', '.':
				fallthrough
			case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
				fallthrough
			case 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z':
				fallthrough
			case '_':
				fallthrough
			case 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z':
				goto yy102
			case '}':
				goto yy104
			default:
				goto yy103
			}
		yy103:
			cursor = marker
			goto yy90
		yy104:
			cursor += 1
			{
				eval.AddSpecial(string(l.input[start+2 : cursor-1]))
				continue
			}
		}

	}

done:
	l.lastToken = start
	l.ofs = cursor
	if path {
		l.EatWhitespace()
	}
	// Non-path strings end in newlines, so there's no whitespace to eat.
	return eval, nil
}
