// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: proto/build_status.proto

package build_status

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The end result of the Build.
type BuildStatus_Result int32

const (
	// Unspecified or unknown.
	BuildStatus_UNKNOWN_STATUS BuildStatus_Result = 0
	// Build was successful and tests (if requested) all pass.
	BuildStatus_COMMAND_SUCCEEDED BuildStatus_Result = 1
	// Build error and/or test failure.
	BuildStatus_COMMAND_FAILED BuildStatus_Result = 2
	// Unable to obtain a result due to input provided by the user.
	BuildStatus_USER_ERROR BuildStatus_Result = 3
	// Unable to obtain a result due to a failure within the build system.
	BuildStatus_SYSTEM_ERROR BuildStatus_Result = 4
	// Build required too many resources, such as build tool RAM.
	BuildStatus_RESOURCE_EXHAUSTED BuildStatus_Result = 5
	// An invocation attempt time exceeded its deadline.
	BuildStatus_INVOCATION_DEADLINE_EXCEEDED BuildStatus_Result = 6
	// Build request time exceeded the request_deadline
	BuildStatus_REQUEST_DEADLINE_EXCEEDED BuildStatus_Result = 8
	// The build was cancelled by a call to CancelBuild.
	BuildStatus_CANCELLED BuildStatus_Result = 7
)

// Enum value maps for BuildStatus_Result.
var (
	BuildStatus_Result_name = map[int32]string{
		0: "UNKNOWN_STATUS",
		1: "COMMAND_SUCCEEDED",
		2: "COMMAND_FAILED",
		3: "USER_ERROR",
		4: "SYSTEM_ERROR",
		5: "RESOURCE_EXHAUSTED",
		6: "INVOCATION_DEADLINE_EXCEEDED",
		8: "REQUEST_DEADLINE_EXCEEDED",
		7: "CANCELLED",
	}
	BuildStatus_Result_value = map[string]int32{
		"UNKNOWN_STATUS":               0,
		"COMMAND_SUCCEEDED":            1,
		"COMMAND_FAILED":               2,
		"USER_ERROR":                   3,
		"SYSTEM_ERROR":                 4,
		"RESOURCE_EXHAUSTED":           5,
		"INVOCATION_DEADLINE_EXCEEDED": 6,
		"REQUEST_DEADLINE_EXCEEDED":    8,
		"CANCELLED":                    7,
	}
)

func (x BuildStatus_Result) Enum() *BuildStatus_Result {
	p := new(BuildStatus_Result)
	*p = x
	return p
}

func (x BuildStatus_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildStatus_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_build_status_proto_enumTypes[0].Descriptor()
}

func (BuildStatus_Result) Type() protoreflect.EnumType {
	return &file_proto_build_status_proto_enumTypes[0]
}

func (x BuildStatus_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildStatus_Result.Descriptor instead.
func (BuildStatus_Result) EnumDescriptor() ([]byte, []int) {
	return file_proto_build_status_proto_rawDescGZIP(), []int{0, 0}
}

// Status used for both invocation attempt and overall build completion.
type BuildStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The end result.
	Result BuildStatus_Result `protobuf:"varint,1,opt,name=result,proto3,enum=google.devtools.build.v1.BuildStatus_Result" json:"result,omitempty"`
	// Final invocation ID of the build, if there was one.
	// This field is only set on a status in BuildFinished event.
	FinalInvocationId string `protobuf:"bytes,3,opt,name=final_invocation_id,json=finalInvocationId,proto3" json:"final_invocation_id,omitempty"`
	// Build tool exit code. Integer value returned by the executed build tool.
	// Might not be available in some cases, e.g., a build timeout.
	BuildToolExitCode *wrapperspb.Int32Value `protobuf:"bytes,4,opt,name=build_tool_exit_code,json=buildToolExitCode,proto3" json:"build_tool_exit_code,omitempty"`
	// Fine-grained diagnostic information to complement the status.
	Details       *anypb.Any `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildStatus) Reset() {
	*x = BuildStatus{}
	mi := &file_proto_build_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStatus) ProtoMessage() {}

func (x *BuildStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_build_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStatus.ProtoReflect.Descriptor instead.
func (*BuildStatus) Descriptor() ([]byte, []int) {
	return file_proto_build_status_proto_rawDescGZIP(), []int{0}
}

func (x *BuildStatus) GetResult() BuildStatus_Result {
	if x != nil {
		return x.Result
	}
	return BuildStatus_UNKNOWN_STATUS
}

func (x *BuildStatus) GetFinalInvocationId() string {
	if x != nil {
		return x.FinalInvocationId
	}
	return ""
}

func (x *BuildStatus) GetBuildToolExitCode() *wrapperspb.Int32Value {
	if x != nil {
		return x.BuildToolExitCode
	}
	return nil
}

func (x *BuildStatus) GetDetails() *anypb.Any {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_proto_build_status_proto protoreflect.FileDescriptor

const file_proto_build_status_proto_rawDesc = "" +
	"\n" +
	"\x18proto/build_status.proto\x12\x18google.devtools.build.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x19google/protobuf/any.proto\"\xd5\x03\n" +
	"\vBuildStatus\x12D\n" +
	"\x06result\x18\x01 \x01(\x0e2,.google.devtools.build.v1.BuildStatus.ResultR\x06result\x12.\n" +
	"\x13final_invocation_id\x18\x03 \x01(\tR\x11finalInvocationId\x12L\n" +
	"\x14build_tool_exit_code\x18\x04 \x01(\v2\x1b.google.protobuf.Int32ValueR\x11buildToolExitCode\x12.\n" +
	"\adetails\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\adetails\"\xd1\x01\n" +
	"\x06Result\x12\x12\n" +
	"\x0eUNKNOWN_STATUS\x10\x00\x12\x15\n" +
	"\x11COMMAND_SUCCEEDED\x10\x01\x12\x12\n" +
	"\x0eCOMMAND_FAILED\x10\x02\x12\x0e\n" +
	"\n" +
	"USER_ERROR\x10\x03\x12\x10\n" +
	"\fSYSTEM_ERROR\x10\x04\x12\x16\n" +
	"\x12RESOURCE_EXHAUSTED\x10\x05\x12 \n" +
	"\x1cINVOCATION_DEADLINE_EXCEEDED\x10\x06\x12\x1d\n" +
	"\x19REQUEST_DEADLINE_EXCEEDED\x10\b\x12\r\n" +
	"\tCANCELLED\x10\aB\x81\x01\n" +
	"\x1ccom.google.devtools.build.v1B\x10BuildStatusProtoP\x01Z2github.com/buildbuddy-io/gin/genproto/build_status\xf8\x01\x01\xca\x02\x15Google\\Cloud\\Build\\V1b\x06proto3"

var (
	file_proto_build_status_proto_rawDescOnce sync.Once
	file_proto_build_status_proto_rawDescData []byte
)

func file_proto_build_status_proto_rawDescGZIP() []byte {
	file_proto_build_status_proto_rawDescOnce.Do(func() {
		file_proto_build_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_build_status_proto_rawDesc), len(file_proto_build_status_proto_rawDesc)))
	})
	return file_proto_build_status_proto_rawDescData
}

var file_proto_build_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_build_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_build_status_proto_goTypes = []any{
	(BuildStatus_Result)(0),       // 0: google.devtools.build.v1.BuildStatus.Result
	(*BuildStatus)(nil),           // 1: google.devtools.build.v1.BuildStatus
	(*wrapperspb.Int32Value)(nil), // 2: google.protobuf.Int32Value
	(*anypb.Any)(nil),             // 3: google.protobuf.Any
}
var file_proto_build_status_proto_depIdxs = []int32{
	0, // 0: google.devtools.build.v1.BuildStatus.result:type_name -> google.devtools.build.v1.BuildStatus.Result
	2, // 1: google.devtools.build.v1.BuildStatus.build_tool_exit_code:type_name -> google.protobuf.Int32Value
	3, // 2: google.devtools.build.v1.BuildStatus.details:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_build_status_proto_init() }
func file_proto_build_status_proto_init() {
	if File_proto_build_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_build_status_proto_rawDesc), len(file_proto_build_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_build_status_proto_goTypes,
		DependencyIndexes: file_proto_build_status_proto_depIdxs,
		EnumInfos:         file_proto_build_status_proto_enumTypes,
		MessageInfos:      file_proto_build_status_proto_msgTypes,
	}.Build()
	File_proto_build_status_proto = out.File
	file_proto_build_status_proto_goTypes = nil
	file_proto_build_status_proto_depIdxs = nil
}
