// Code generated by re2go 4.3 on Sun Sep  7 15:00:49 2025, DO NOT EDIT.
//
//line "internal/depfile_parser/depfile_parser.go.in":1
package depfile_parser

import (
	"fmt"
	"slices"
)

type DepfileParserOptions struct{}

func DefaultOptions() DepfileParserOptions {
	return DepfileParserOptions{}
}

type DepfileParser struct {
	outs    []string
	ins     []string
	options DepfileParserOptions
}

// New creates a new ManifestParser
func New(options DepfileParserOptions) *DepfileParser {
	return &DepfileParser{
		outs:    make([]string, 0),
		ins:     make([]string, 0),
		options: options,
	}
}

// Returns "fake" terminating null if cursor has reached limit.
func peek(str []byte, cursor, limit int) byte {
	if cursor >= limit {
		return 0 // fake null
	} else {
		return str[cursor]
	}
}

func (p *DepfileParser) Ins() []string {
	return p.ins
}

func (p *DepfileParser) Outs() []string {
	return p.outs
}

func memset(arr []byte, chr byte) {
	for i := range arr {
		arr[i] = chr
	}
}

func memmov(dst, src []byte, n int) {
	copy(dst, src[:n])
}

func (p *DepfileParser) Parse(content string) error {
	// Convert string to byte slice for processing
	contentBytes := []byte(content)

	// in: current parser input point.
	// end: end of input.
	// parsingTargets: whether we are parsing targets or dependencies.
	cursor := 0
	limit := len(contentBytes)
	haveTarget := false
	parsingTargets := true
	poisonedInput := false
	isEmpty := true

	for cursor < limit {
		haveNewline := false
		// out: current output point (typically same as in, but can fall behind
		// as we de-escape backslashes).
		outIdx := cursor
		// filename: start of the current parsed filename.
		filenameIdx := outIdx

		for {
			// start: beginning of the current parsed span.
			start := cursor
			var marker int

//line "internal/depfile_parser/depfile_parser.go":87
			{
				var yych byte
				yych = peek(contentBytes, cursor, limit)
				switch yych {
				case 0x00:
					goto yy1
				case 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, '\t':
					fallthrough
				case '\v', '\f':
					fallthrough
				case 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, ' ':
					fallthrough
				case '#':
					fallthrough
				case '*':
					fallthrough
				case ';', '<':
					fallthrough
				case '>':
					fallthrough
				case '^':
					fallthrough
				case '`':
					fallthrough
				case '|':
					fallthrough
				case 0x7F:
					goto yy2
				case '\n':
					goto yy4
				case '\r':
					goto yy5
				case '$':
					goto yy8
				case '\\':
					goto yy9
				default:
					goto yy6
				}
			yy1:
				cursor += 1
//line "internal/depfile_parser/depfile_parser.go.in":173
				{
					break
				}
//line "internal/depfile_parser/depfile_parser.go":133
			yy2:
				cursor += 1
			yy3:
//line "internal/depfile_parser/depfile_parser.go.in":185
				{
					// For any other character (e.g. whitespace), swallow it here,
					// allowing the outer logic to loop around again.
					break
				}
//line "internal/depfile_parser/depfile_parser.go":143
			yy4:
				cursor += 1
//line "internal/depfile_parser/depfile_parser.go.in":180
				{
					// A newline ends the current file name and the current rule.
					haveNewline = true
					break
				}
//line "internal/depfile_parser/depfile_parser.go":152
			yy5:
				cursor += 1
				yych = peek(contentBytes, cursor, limit)
				switch yych {
				case '\n':
					goto yy4
				default:
					goto yy3
				}
			yy6:
				cursor += 1
				yych = peek(contentBytes, cursor, limit)
				switch yych {
				case 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, '\t', '\n', '\v', '\f', '\r', 0x0E, 0x0F, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, ' ':
					fallthrough
				case '#', '$':
					fallthrough
				case '*':
					fallthrough
				case ';', '<':
					fallthrough
				case '>':
					fallthrough
				case '\\':
					fallthrough
				case '^':
					fallthrough
				case '`':
					fallthrough
				case '|':
					fallthrough
				case 0x7F:
					goto yy7
				default:
					goto yy6
				}
			yy7:
//line "internal/depfile_parser/depfile_parser.go.in":163
				{
					// Got a span of plain text.
					length := cursor - start
					// Need to shift it over if we're overwriting backslashes.
					if outIdx < start {
						memmov(contentBytes[outIdx:], contentBytes[start:], length)
					}
					outIdx += length
					continue
				}
//line "internal/depfile_parser/depfile_parser.go":201
			yy8:
				cursor += 1
				yych = peek(contentBytes, cursor, limit)
				switch yych {
				case '$':
					goto yy10
				default:
					goto yy3
				}
			yy9:
				cursor += 1
				marker = cursor
				yych = peek(contentBytes, cursor, limit)
				switch yych {
				case 0x00:
					goto yy3
				case '\n':
					goto yy12
				case '\r':
					goto yy13
				case ' ':
					goto yy15
				case '#':
					goto yy16
				case ':':
					goto yy17
				case '\\':
					goto yy19
				default:
					goto yy11
				}
			yy10:
				cursor += 1
//line "internal/depfile_parser/depfile_parser.go.in":157
				{
					// De-escape dollar character.
					contentBytes[outIdx] = '$'
					outIdx++
					continue
				}
//line "internal/depfile_parser/depfile_parser.go":242
			yy11:
				cursor += 1
				goto yy7
			yy12:
				cursor += 1
//line "internal/depfile_parser/depfile_parser.go.in":176
				{
					// A line continuation ends the current file name.
					break
				}
//line "internal/depfile_parser/depfile_parser.go":253
			yy13:
				cursor += 1
				yych = peek(contentBytes, cursor, limit)
				switch yych {
				case '\n':
					goto yy12
				default:
					goto yy14
				}
			yy14:
				cursor = marker
				goto yy3
			yy15:
				cursor += 1
//line "internal/depfile_parser/depfile_parser.go.in":98
				{
					// 2N+1 backslashes plus space -> N backslashes plus space.
					length := cursor - start
					n := length/2 - 1
					if outIdx < start {
						memset(contentBytes[outIdx:outIdx+n], '\\')
					}
					outIdx += n
					contentBytes[outIdx] = ' '
					outIdx++
					continue
				}
//line "internal/depfile_parser/depfile_parser.go":281
			yy16:
				cursor += 1
//line "internal/depfile_parser/depfile_parser.go.in":119
				{
					// De-escape hash sign, but preserve other leading backslashes.
					length := cursor - start
					if length > 2 && outIdx < start {
						memset(contentBytes[outIdx:outIdx+length-2], '\\')
					}
					outIdx += length - 2
					contentBytes[outIdx] = '#'
					outIdx++
					continue
				}
//line "internal/depfile_parser/depfile_parser.go":296
			yy17:
				cursor += 1
				yych = peek(contentBytes, cursor, limit)
				switch yych {
				case 0x00:
					fallthrough
				case '\t', '\n':
					fallthrough
				case '\r':
					fallthrough
				case ' ':
					goto yy20
				default:
					goto yy18
				}
			yy18:
//line "internal/depfile_parser/depfile_parser.go.in":144
				{
					// De-escape colon sign, but preserve other leading backslashes.
					// Regular expression uses lookahead to make sure that no whitespace
					// nor EOF follows. In that case it'd be the : at the end of a target
					length := cursor - start
					if length > 2 && outIdx < start {
						memset(contentBytes[outIdx:outIdx+length-2], '\\')
					}
					outIdx += length - 2
					contentBytes[outIdx] = ':'
					outIdx++
					continue
				}
//line "internal/depfile_parser/depfile_parser.go":327
			yy19:
				cursor += 1
				yych = peek(contentBytes, cursor, limit)
				switch yych {
				case 0x00:
					fallthrough
				case '\n':
					fallthrough
				case '\r':
					goto yy7
				case ' ':
					goto yy21
				case '#':
					goto yy16
				case ':':
					goto yy17
				case '\\':
					goto yy22
				default:
					goto yy11
				}
			yy20:
				cursor += 1
//line "internal/depfile_parser/depfile_parser.go.in":130
				{
					// Backslash followed by : and whitespace.
					// It is therefore normal text and not an escaped colon
					length := cursor - start - 1
					// Need to shift it over if we're overwriting backslashes.
					if outIdx < start {
						memmov(contentBytes[outIdx:], contentBytes[start:], length)
					}
					outIdx += length
					if peek(contentBytes, cursor-1, limit) == '\n' {
						haveNewline = true
					}
					break
				}
//line "internal/depfile_parser/depfile_parser.go":366
			yy21:
				cursor += 1
//line "internal/depfile_parser/depfile_parser.go.in":110
				{
					// 2N backslashes plus space -> 2N backslashes, end of filename.
					length := cursor - start
					if outIdx < start {
						memset(contentBytes[outIdx:outIdx+length-1], '\\')
					}
					outIdx += length - 1
					break
				}
//line "internal/depfile_parser/depfile_parser.go":379
			yy22:
				cursor += 1
				yych = peek(contentBytes, cursor, limit)
				switch yych {
				case 0x00:
					fallthrough
				case '\n':
					fallthrough
				case '\r':
					goto yy7
				case ' ':
					goto yy15
				case '#':
					goto yy16
				case ':':
					goto yy17
				case '\\':
					goto yy19
				default:
					goto yy11
				}
			}
//line "internal/depfile_parser/depfile_parser.go.in":190

		}

		length := outIdx - filenameIdx
		isDependency := !parsingTargets
		if length > 0 && contentBytes[filenameIdx+length-1] == ':' {
			length-- // Strip off trailing colon, if any.
			parsingTargets = false
			haveTarget = true
		}

		if length > 0 {
			isEmpty = false
			piece := string(contentBytes[filenameIdx : filenameIdx+length])
			// If we've seen this as an input before, skip it.
			pos := slices.Index(p.ins, piece)
			if pos == -1 {
				if isDependency {
					if poisonedInput {
						return fmt.Errorf("inputs may not also have inputs")
					}
					// New input.
					p.ins = append(p.ins, piece)
				} else {
					// Check for a new output.
					if slices.Index(p.outs, piece) == -1 {
						p.outs = append(p.outs, piece)
					}
				}
			} else if !isDependency {
				// We've passed an input on the left side; reject new inputs.
				poisonedInput = true
			}
		}

		if haveNewline {
			// A newline ends a rule so the next filename will be a new target.
			parsingTargets = true
			poisonedInput = false
		}
	}

	if !haveTarget && !isEmpty {
		return fmt.Errorf("expected ':' in depfile")
	}
	return nil
}
