package missing_deps

import (
	"fmt"
	"maps"
	"slices"

	"github.com/buildbuddy-io/reninja/internal/depfile_parser"
	"github.com/buildbuddy-io/reninja/internal/deps_log"
	"github.com/buildbuddy-io/reninja/internal/disk"
	"github.com/buildbuddy-io/reninja/internal/eval_env"
	"github.com/buildbuddy-io/reninja/internal/graph"
	"github.com/buildbuddy-io/reninja/internal/implicit_dep_loader"
	"github.com/buildbuddy-io/reninja/internal/state"
)

type InnerAdjacencyMap map[*graph.Edge]struct{}
type AdjacencyMap map[*graph.Edge]InnerAdjacencyMap

type MissingDependencyScannerDelegate interface {
	OnMissingDep(node *graph.Node, path string, generator *eval_env.Rule)
}

// Ensure eMissingDependencyPrinter implements MissingDependencyScannerDelegate.
var _ MissingDependencyScannerDelegate = &MissingDependencyPrinter{}

type MissingDependencyPrinter struct{}

func (p *MissingDependencyPrinter) OnMissingDep(node *graph.Node, path string, generator *eval_env.Rule) {
	fmt.Printf("Missing dep: %s uses %s (generated by %s)\n", node.Path(), path, generator.Name())
}

type MissingDependencyScanner struct {
	delegate            MissingDependencyScannerDelegate
	depsLog             *deps_log.DepsLog
	state               *state.State
	diskInterface       disk.Interface
	seen                map[*graph.Node]struct{}
	nodesMissingDeps    map[*graph.Node]struct{}
	generatedNodes      map[*graph.Node]struct{}
	generatorRules      map[*eval_env.Rule]struct{}
	missingDepPathCount int
	adjacencyMap        AdjacencyMap
}

func NewScanner(delegate MissingDependencyScannerDelegate, depsLog *deps_log.DepsLog, state *state.State, diskInterface disk.Interface) *MissingDependencyScanner {
	return &MissingDependencyScanner{
		delegate:            delegate,
		depsLog:             depsLog,
		state:               state,
		diskInterface:       diskInterface,
		seen:                make(map[*graph.Node]struct{}, 0),
		nodesMissingDeps:    make(map[*graph.Node]struct{}, 0),
		generatedNodes:      make(map[*graph.Node]struct{}, 0),
		generatorRules:      make(map[*eval_env.Rule]struct{}, 0),
		missingDepPathCount: 0,
		adjacencyMap:        make(map[*graph.Edge]InnerAdjacencyMap, 0),
	}
}

func (s *MissingDependencyScanner) ProcessNode(node *graph.Node) {
	if node == nil {
		return
	}
	edge := node.InEdge()
	if edge == nil {
		return
	}
	if _, ok := s.seen[node]; ok {
		return
	}
	s.seen[node] = struct{}{}

	for _, in := range edge.Inputs() {
		s.ProcessNode(in)
	}

	depsType := edge.GetBinding("deps")
	if depsType != "" {
		deps := s.depsLog.GetDeps(node)
		if deps != nil {
			s.ProcessNodeDeps(node, deps.Nodes)
		}
	} else {
		parserOpts := depfile_parser.DepfileParserOptions{}
		depLoader := implicit_dep_loader.NewNodeStoringImplicitDepLoader(s.state, s.depsLog, s.diskInterface, parserOpts, nil)
		loaded, err := depLoader.LoadDeps(edge)
		if err != nil {
			fmt.Printf("LoadDeps err: %s", err)
		}
		if !loaded {
			fmt.Printf("loaded was false!")
		}
		depfileDeps := depLoader.DepNodesOutput()
		if err == nil && loaded && len(depfileDeps) > 0 {
			s.ProcessNodeDeps(node, depfileDeps)
		}
	}
}

func (s *MissingDependencyScanner) ProcessNodeDeps(node *graph.Node, depNodes []*graph.Node) {
	edge := node.InEdge()
	deplogEdges := make(map[*graph.Edge]struct{}, 0)
	for _, deplogNode := range depNodes {
		// Special exception: A dep on build.ninja can be used to mean "always
		// rebuild this target when the build is reconfigured", but build.ninja is
		// often generated by a configuration tool like cmake or gn. The rest of
		// the build "implicitly" depends on the entire build being reconfigured,
		// so a missing dep path to build.ninja is not an actual missing dependency
		// problem.
		if deplogNode.Path() == "build.ninja" {
			return
		}
		if deplogEdge := deplogNode.InEdge(); deplogEdge != nil {
			deplogEdges[deplogEdge] = struct{}{}
		}
	}
	missingDeps := make([]*graph.Edge, 0)
	for de := range deplogEdges {
		if !s.PathExistsBetween(de, edge) {
			missingDeps = append(missingDeps, de)
		}
	}

	if len(missingDeps) > 0 {
		missingDepsRuleNames := make(map[string]struct{})
		for _, ne := range missingDeps {
			for _, depNode := range depNodes {
				if depNode.InEdge() == ne {
					s.generatedNodes[depNode] = struct{}{}
					s.generatorRules[ne.Rule()] = struct{}{}
					missingDepsRuleNames[ne.Rule().Name()] = struct{}{}
					s.delegate.OnMissingDep(node, depNode.Path(), ne.Rule())
				}
			}
		}
		s.missingDepPathCount += len(missingDepsRuleNames)
		s.nodesMissingDeps[node] = struct{}{}
	}
}

func (s *MissingDependencyScanner) PrintStats() {
	fmt.Printf("Processed %d nodes.\n", len(s.seen))
	if s.HadMissingDeps() {
		fmt.Printf("Error: There are %d missing dependency paths.\n", s.missingDepPathCount)
		fmt.Printf("%d targets had depfile dependencies on ", len(s.nodesMissingDeps))
		fmt.Printf("%d distinct generated inputs (from %d rules) ", len(s.generatedNodes), len(s.generatorRules))
		fmt.Printf(" without a non-depfile dep path to the generator.\n")
		fmt.Printf("There might be build flakiness if any of the targets listed ")
		fmt.Printf("above are built alone, or not late enough, in a clean output ")
		fmt.Printf("directory.\n")
	} else {
		fmt.Printf("No missing dependencies on generated files found.\n")
	}
}

func (s *MissingDependencyScanner) PathExistsBetween(from, to *graph.Edge) bool {
	innerAdjacencyMap, ok := s.adjacencyMap[from]
	if ok {
		if _, ok = innerAdjacencyMap[to]; ok {
			return ok
		}
	} else {
		s.adjacencyMap[from] = make(InnerAdjacencyMap, 0)
	}
	found := false
	for _, in := range to.Inputs() {
		e := in.InEdge()
		if e != nil && (e == from || s.PathExistsBetween(from, e)) {
			found = true
			break
		}
	}
	s.adjacencyMap[from][to] = struct{}{}
	return found
}

func (s *MissingDependencyScanner) HadMissingDeps() bool {
	return len(s.nodesMissingDeps) > 0
}

func (s *MissingDependencyScanner) NodesMissingDeps() []*graph.Node {
	return slices.Collect(maps.Keys(s.nodesMissingDeps))
}

func (s *MissingDependencyScanner) MissingDepPathCount() int {
	return s.missingDepPathCount
}

func (s *MissingDependencyScanner) GeneratedNodes() []*graph.Node {
	return slices.Collect(maps.Keys(s.generatedNodes))
}

func (s *MissingDependencyScanner) GeneratorRules() []*eval_env.Rule {
	return slices.Collect(maps.Keys(s.generatorRules))
}
